config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books
  resources :subjects
  root "home#index"

  resources :publishers, only: [:index, :show] do
    resources :books, only: [:index, :show]
  end
  resources :libraries, only: [:index, :show] do
    resources :copies, controller: "libraries/copies", only: [:index, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_and_belongs_to_many :subjects, optional: true
  belongs_to :publisher, optional: true
  has_many :copies
  has_many :libraries, through: :copies
  has_one_attached :cover
  validates_presence_of :title
  validates_numericality_of :price, allow_nil: true, message: "Make sure price is a number"

  def subjects_list
    subjects.map(&:name).to_sentence
  end
end

app/models/copy.rb
class Copy < ApplicationRecord
  belongs_to :book
  belongs_to :library
end

app/models/library.rb
class Library < ApplicationRecord
  has_many :copies
  has_many :books, through: :copies
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_and_belongs_to_many :books
  validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/book_controller.rb
class BookController < ApplicationController

    layout 'standard'
    
    def list
        @books=Book.all
    end

    def show
        @book=Book.find(params[:id])
    end

    def new
        @book=Book.new
        @subjects=Subject.all
    end

    def book_params
        params.require(:books).permit(:title, :price, :subject_id, :description)
     end
  
     def create
        @book = Book.new(book_params)
  
        if @book.save
           redirect_to :action => 'list'
#Allow for empty subject
        # elsif @book.subject==false
        #     @book.subject_id="Physics"
        else
           @subjects = Subject.all
           flash[:errors] = @book.errors.full_messages
           render :action => 'new'
        end
     end

    def edit
        @book=Book.find(params[:id])
        @subjects=Subject.all
    end

    def book_param
        params.require(:book).permit(:title, :price, :subject_id, :description)
    end

    def update
        @book=Book.find(params[:id])

        if @book.update_attributes(book_param)
            redirect_to :action => 'show', :id => @book
        else 
            @subjects=Subject.all
            render :action => 'edit'
        end

    end

    def delete
        Book.find(params[:id]).destroy
        redirect_to :action => 'list'
    end

    def show_subjects
        @subject = Subject.find(params[:id])
    end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books_count = Book.count
    @q = Book.ransack(params[:q])
    @books = @q.result(distinct: true)
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
    if params[:subject_id]
      @book.subject_id = params[:subject_id]
    end
  end

  def create
    @book = Book.new(book_param)
    if @book.save
      redirect_to books_path
    else
      flash[:errors] = @book.errors.full_messages
      render action: "new"
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def book_param
    params.require(:book).permit(:title, :price, :subject_id, :description)
  end

  def update
    @book = Book.find(params[:id])

    if @book.update_attributes(book_param)
      redirect_to action: "show", id: @book
    else
      render action: "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    if params[:path] && params[:path] == "subject_index"
      redirect_to subjects_path
    elsif params[:subject_id]
      redirect_to subject_path(params[:subject_id]) # If being viewed from a subject show page, then the book has a subject --> this is a safe call
    else
      redirect_to action: "index"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @books = Book.last(5).reverse
    @subjects = Subject.last(5).reverse
    @publishers = Publisher.last(5).reverse
    @libraries = Library.last(5).reverse
  end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  def show
    @library = Library.find(params[:id])
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def show
    @publisher = Publisher.find(params[:id])
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
    @q = Subject.ransack(params[:q])
    @subjects = @q.result(distinct: true)
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(subject_param)
    if @subject.save
      redirect_to subjects_path
    else
      flash[:errors] = @subject.errors.full_messages
      render action: "new"
    end
  end

  def subject_param
    params.require(:subject).permit(:name)
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    @subject = Subject.find(params[:id])

    if @subject.update_attributes(subject_param)
      redirect_to action: "show", id: @subject
    else
      render action: "edit"
    end
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    redirect_to action: "index"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/admin/_header.html.haml
%p{style: 'padding-top:15px;'}
  = link_to destroy_session_path(:user), :method => :delete do
    %i.fa.fa-sign-out
    Logout

app/views/admin/subjects/not_included_index.html.haml
- @subjects.each do |subject|
    %h1
        = link_to subject.name, subjects_admin_path(subject)
        = link_to "Edit", edit_subjects_admin_path(subject)
        = link_to "Delete", subjects_admin_path(subject), method: :delete, data: {confirm: "Are you sure?"}
    - subject.books.each do |book|
        %p
        %li
            = link_to book.title, books_admin_path(book)
            %b= link_to 'Edit', edit_books_admin_path(book)
            %b= link_to 'Delete', books_admin_path(book, path: "subject_index"), method: :delete, data: {confirm: "Are you sure?"}

app/views/book/edit.html.haml
%h1 Edit Book Detail

= form_for @book, :url =>{:action => "update", :id =>@book} do |f|
    .row
        %p 
            Title: 
            = f.text_field 'title'
    .row
        %p 
            Price: 
            = f.text_field 'price'
    .row
        %p 
            Subject: 
            = f.collection_select :subject_id, Subject.all, :id, :name
    %p
        Description:  
        %br
        = f.text_area 'description'
        
    = f.submit "Save changes"
    %br
    = link_to 'Back', {:action => 'list'}

app/views/book/new.html.haml
- if @book.errors.any?
  #error_explanation
    %h2
      = pluralize(@book.errors.count, "error")
      prohibited this book from being saved:
    %ul
      - @book.errors.full_messages.each do |msg|
        %li= msg
%h1 Add new book
= form_tag :action => 'create' do
  %p
    %label{:for => "book_title"}> Title
    \:
    = text_field 'books', 'title'
  %p
    %label{:for => "book_price"}> Price
    \:
    = text_field 'books', 'price'
  %p
    %label{:for => "book_subject_id"}> Subject
    \:
    = collection_select(:books, :subject_id, @subjects, :id, :name, prompt: true)
  %p
    %label{:for => "book_description"} Description
    %br/
    = text_area 'books', 'description'
  = submit_tag "Create"
= link_to 'Back', {:action => 'list'}

app/views/books/_form.html.haml
=form_with(model: book, local: true) do |form|
  .form-group
    = form.label :title
    \:
    = form.text_field :title, :class => "form-control"
  .row
    .col-2
    .col-4
      .form-group
        = form.label :price
        \:
        = form.text_field :price, :class => "form-control"
    .col-2
      .form-group
        = form.label :subject
        \:
        = form.collection_select :subject_ids, Subject.all, :id, :name, {}, multiple: true
  .form-group
    = form.label :description
    \:
    = form.text_area :description, :class => "form-control"
  .my-3= form.submit :Save, :class => "btn btn-primary"

app/views/books/edit.html.haml
%h3.text-center.my-3 Edit Book Detail

.row.text-center
  .mx-auto.col-8
    = render 'form', book: @book
    = link_to 'Back', books_path, :class => "btn btn-primary btn-sm text-light my-3"

app/views/books/index.html.haml
%h3.text-center.my-3 Subjects:
%ul.list-group.list-group-horizontal
  - Subject.all.each do |c|
    %li.list-group-item.list-group-item-primary.d-flex.justify-content-between.align-items-center
      = link_to c.name, subject_path(c), :class => "text-secondary"
      %span.badge.badge-primary.badge-pill.ml-3= c.books.count

%h3.my-2 Books: 
=search_form_for @q do |f|
  .form-group.row
    .col
      =f.search_field :title_cont, :class => "form-control"
    .col
      =f.submit :class => "btn btn-primary btn-sm"
- if @books.empty?
  %h5.text-center.mt-4 There are not any books to display.

%ul.list-group
  - @books.each do |c|
    %li.list-group-item.d-flex.text-center
      %strong.mr-auto.p-2= link_to c.title, book_path(c)
      = link_to 'Edit', edit_book_path(c), :class => "btn btn-primary btn-sm text-light mx-2"
      = link_to 'Delete', book_path(c), method: :delete, data: {confirm: "Are you sure?" }, :class => "btn btn-primary btn-sm text-light mx-2"

app/views/books/new.html.haml
%h3.text-center.my-3 New Book Entry

.row.text-center
  .mx-auto.col-8
    = render 'form', book: @book
    = link_to 'Back', books_path, :class => "btn btn-primary btn-sm text-light my-3"

app/views/books/show.html.haml
.row
  .col.my-3.mr-3
    %h1= @book.title
    %p
      %strong Price:
      -if @book.price
        $#{@book.price}
      -else
        = "\"Priceless\""
      %br
      %strong Subjects:
      -if @book.subjects.any?
        - @book.subjects.all.each do |c|
          = link_to c.name, subject_path(c)
      -else
        = "No Subject"
      %br
      %strong Created Date:
      = @book.created_at
      %br
    %strong Description: 
    %hr
    %p= @book.description
    %hr
    
    %strong Copies in the system: 
    = @book.copies.count
    %br
    %strong Libraries with this book: 
    -if @book.libraries.any?
      - @book.libraries.distinct.each do |c|
        %li
          =c.name
          \:
          -if c.copies.where("book_id = ? AND checked_out = ?", @book.id, false)
            =pluralize(c.copies.where("book_id = ? AND checked_out = ?", @book.id, false).count , "copy")
            in stock
            
    -else
      None in stock
    .mt-4
      = link_to 'Back', books_path, :class => "btn btn-primary btn-sm text-light mr-3"
      = link_to 'Edit', edit_book_path(@book), :class => "btn btn-primary btn-sm text-light mr-3"
      = link_to 'Delete', book_path(@book), method: :delete, data: {confirm: "Are you sure?"}, :class => "btn btn-primary btn-sm text-light mr-3"
  .col.mt-3.ml-3.text-center
    =image_tag(@book.cover, size: "400x600")

app/views/home/index.html.haml
.jumbotron
  %h1.display-4
    A library cataloging solution
  %p.lead
    Store your books with ease.
.row
  .col
    .card
      .card-title.text-center.my-2 Most recent books
      .card-body
        %ul.list-group
          - @books.each do |book|
            %li.list-group-item= link_to book.title, book_path(book)
        .card-link.text-center.mt-2
          = link_to "View all", books_path, :class => "btn btn-primary"
  .col
    .card
      .card-title.text-center.my-2 Most Recent Subjects
      .card-body
        %ul.list-group
          - @subjects.each do |subject|
            %li.list-group-item= link_to subject.name, subject_path(subject)
        .card-link.text-center.mt-2
          = link_to "View all", subjects_path, :class => "btn btn-primary"
.row.mt-4
  .col
    .card
      .card-title.text-center.my-2 Most Recent Publishers
      .card-body
        %ul.list-group
          - @publishers.each do |c|
            %li.list-group-item= link_to c.name, publisher_path(c)
  .col
    .card
      .card-title.text-center.my-2 Newest Libraries
      .card-body
        %ul.list-group
          - @libraries.each do |c|
            %li.list-group-item= link_to c.name, library_path(c)

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
    = csp_meta_tag
  %body
    .container
      %nav.navbar.navbar-expand-lg.navbar-dark.bg-primary.text-white
        .navbar-brand 
          = link_to "Library Info System", root_path, :class => "navbar text-light"

        #navbarSupportedContent.collapse.navbar-collapse
          %ul.navbar-nav.ml-auto
            %li.nav-item.dropdown
              %a#navbarDropdown.nav-link.dropdown-toggle.text-light{"data-toggle" => "dropdown", :href => "#"} Catalog
              .dropdown-menu
                .dropdown-item 
                  =link_to "All books", books_path
                .dropdown-item
                  =link_to "Subject view", subjects_path
                .dropdown-item
                  =link_to "Admin page", trestle_path
            %li.nav-item.dropdown
              %a#navbarDropdown.nav-link.dropdown-toggle.text-light{"data-toggle" => "dropdown", :href => "#"} Libraries
              .dropdown-menu
                -Library.all.each do |c|
                  .dropdown-item
                    =link_to c.name, library_path(c)
            %li.nav-item.dropdown
              %a#navbarDropdown.nav-link.dropdown-toggle.text-light{"data-toggle" => "dropdown", :href => "#"} Publishers
              .dropdown-menu
                -Publisher.all.each do |c|
                  .dropdown-item
                    =link_to c.name, publisher_path(c)
            %li.nav-item
              = link_to "Logout", destroy_user_session_path, method: :delete, :class => "navbar text-light"
            %li.nav-item
              = link_to "Account", edit_user_registration_path, :class => "navbar text-light"
      .text-danger.text-center
        - flash.each do |name, msg|
          %strong= content_tag :div, msg, class: name

      = yield

app/views/libraries/show.html.haml
.row.mt-2.mb-3
  .col-3
  .col-6.text-center    
    %h1.my-3.text-center
      = @library.name
.row.m-4
  %h2 Libary Stock:
%ul.list-group
  - @library.books.distinct.each do |c|
    %li.list-group-item.d-flex
      %strong.p-2.flex-grow-1= link_to c.title, book_path(c)
.row.text-center
  .col-1
    = link_to 'Back', books_path, :class => "btn btn-primary btn-sm text-light mt-3"

app/views/publishers/show.html.haml
.row.mt-2.mb-3
  .col-3
  .col-6.text-center    
    %h1.my-3.text-center
      = @publisher.name
.row.m-4
  %h2 Books under this publisher: 
%ul.list-group
  - @publisher.books.distinct.each do |c|
    %li.list-group-item.d-flex
      %strong.p-2.flex-grow-1= link_to c.title, book_path(c)
.row.text-center
  .col-1
    = link_to 'Back', books_path, :class => "btn btn-primary btn-sm text-light mt-3"

app/views/subjects/_form.html.haml
=form_with(model: subject, local: true) do |form|
  .form-group
    = form.label :Subject_Name
    \:
    = form.text_field :name, :class => "form-control"
  =form.submit :Save, :class => "btn btn-primary"

app/views/subjects/edit.html.haml
%h3.text-center.mb-5.mt-3 Edit Subject Name

.row.text-center
  .mx-auto.col-8
    = render 'form', subject: @subject
.btn.btn-sm.btn-primary.my-3= link_to 'Back', subjects_path, :class => "btn text-light"

app/views/subjects/index.html.haml
.row
  .col.mt-4
    =search_form_for @q do |f|
      .form-group
        =f.label :subject_search
        \:
        =f.search_field :name_cont, :class => "form-control"
        =f.submit :class => "btn btn-primary btn-sm"
  .col.text-right
    =link_to "Create new subject", new_subject_path, :class => "btn btn-primary my-4 text-center text-light text-right"
.row
  - @subjects.each do |subject|
    .col-4
      .mb-3.card.card-body.border.border-primary
        .card-title
          %strong= link_to subject.name, subject_path(subject)
        %ul.list-group.text-secondary
          - subject.books.each do |book|
            %li.list-group-item
              = link_to book.title, book_path(book)
              %strong.ml-2= link_to 'Edit', edit_book_path(book)
              %strong.ml-2= link_to 'Delete', book_path(book, path: "subject_index"), method: :delete, data: {confirm: "Are you sure?" }
.row
  .col
    = link_to 'Back', books_path, :class => "btn btn-primary btn-sm text-light mr-3"

app/views/subjects/new.html.haml
%h3.text-center.mb-5.mt-3 New Subject

.row.text-center
  .mx-auto.col-8
    = render 'form', subject: @subject
= link_to 'Back', subjects_path, :class => "btn btn-primary btn-sm text-light my-3"

app/views/subjects/show.html.haml
.row.mt-2.mb-3
  .col-3
  .col-6.text-center    
    %h1.my-3.text-center
      = @subject.name
  .col-3.text-center.mt-4
    = link_to 'Edit', edit_subject_path(@subject), :class => "btn btn-primary btn-sm text-light mx-2"
    = link_to 'Delete', subject_path(@subject), method: :delete, data: {confirm: "Are you sure?" }, :class => "btn btn-primary btn-sm text-light mx-2"
%ul.list-group
  - @subject.books.each do |c|
    %li.list-group-item.d-flex
      %strong.p-2.flex-grow-1= link_to c.title, book_path(c)
      = link_to 'Edit', edit_book_path(c), :class => "btn btn-primary btn-sm text-light mx-2"
      = link_to 'Delete', book_path(c, subject_id: @subject.id), method: :delete, data: {confirm: "Are you sure?" }, :class => "btn btn-primary btn-sm text-light mx-2"
.row.text-center
  .col-1
    = link_to 'Back', books_path, :class => "btn btn-primary btn-sm text-light mt-3"
  .col-9
  .col-2
    = link_to "Add New Book", new_book_path(subject_id: @subject.id), :class => "btn btn-primary btn-sm text-light mt-3"